# Custom Language File for Launcher Customizer

[ejs.app]
title = "[ALPHA BUILD] Krakyn Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Kairosen/KrakynLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/Kairosen/KrakynLauncher"
supportLink = "https://github.com/Kairosen/KrakynLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO THE KRAKYN LAUNCHER"
welcomeDescription = "All of our clients, modpacks, and servers are seemlessly managed within this streamlined launcher. Updates are automatic and new clients/modpacks we release will automatically show up here. Join us on our first journey into Prominence II RPG: Hasturian Era. A MASSIVE modpack with 460+ mods, with some further modding by us to add more content like Distant Horizons for example."
welcomeDescCTA = "You are just a few clicks away from joining your grand adventure..."
